name: Test

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: josa42/gha-stylua@main
